### PR TITLE
Update #3

### PR DESCRIPTION
**Pull request by Hawxy**
I found the issues with the source, two of the project files are incorrect. If you have the ability to delete them, please go ahead. I wonder if there is an option so I can direct access to your source.

### CODE REVIEW

**Comment by dkmjr** [comment]
I made an organization, so now you have complete control once I make you owner.

**Comment by Hawxy** [comment]
Awesome, thanks

**Comment by dkmjr** [comment]
ohai I'm busy coding on my mac

**Comment by Hawxy** [comment]
Ahaha, Awesome. :D

**Comment by dkmjr** [comment]
You can make commits without me merging them now.

**Comment by Hawxy** [comment]
Thanks

**Pull request closed without merging**
